Bump to latest Checkra1n version and update to 1.1.7
asineth0/checkn1x pull request #31
Opened 2021-04-30 10:10 UTC by TeGaX

2021-05-01 09:26 UTC, Mehrshadfi commented
Hi
When will the next update come?

2021-05-01 23:04 UTC, TeGaX commented
> Hi
> When will the next update come?

Idk really
Waiting for the dev merge my commit and build it

2021-05-01 23:54 UTC, TeGaX commented
> Hi
> When will the next update come?

Or you can check my Checkn1x repo https://github.com/TeGaX/checkn1x_reborn

It updated to latest Odysseyn1x and Checkra1n

2021-05-02 07:00 UTC, noelff commented
![image](https://user-images.githubusercontent.com/35950582/116805166-16536280-ab57-11eb-9df6-1fb46b886516.jpeg)

2021-05-02 10:37 UTC, realhot commented
![image](https://user-images.githubusercontent.com/74508521/116810253-76dca280-ab4b-11eb-93eb-7c68921ebe7c.jpg)

2021-05-02 21:18 UTC, faheem123456 commented
iOS 14.5 checkr1n iPhone 8 global not supported plz add iPhone 8 global

2021-05-03 00:55 UTC, faheem123456 commented
> No description provided.

iPhone 8 global iOS 14.5 not supported

2021-05-05 22:50 UTC, Favna requested changes

2021-05-05 22:50 UTC, Favna commented on README.md
> +# checkn1x Reborn - bring back Checkn1x with latest Checkra1n version (0.12.3)
You should probably remove this from the PR. It’s fine to have it on your own fork, but then create the PR from another branch at least.

2021-05-05 22:50 UTC, Favna commented on README.md
> +Downloads are available under [releases](https://github.com/TeGaX/checkn1x/releases).
Revert this url

2021-05-05 22:50 UTC, Favna commented on README.md
> +1. Download [Etcher](https://etcher.io), [Rufus](https://rufus.ie) and the ISO from releases.
Etcher works fine, Rufus is not needed. Also Rufus is windows only whereas etcher is cross platform.

2021-05-05 22:50 UTC, Favna commented on README.md
> +## Credits
Remove this

2021-05-05 22:50 UTC, Favna commented on scripts/checkn1x_cliprompt
> +exec /usr/local/bin/checkra1n --cli
Correct me if I’m wrong but I’m pretty sure -c is an alias for —cli and -v for —verbose. If that’s correct (validate with —help) then revert this as the previous flags were fine.

2021-05-06 13:59 UTC, closed without merging